name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - id: dokku
        name: Deploy to dokku
        uses: vitalyliber/dokku-github-action@v4.0
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: 134.122.123.191
          PROJECT: edgsh
  deploy-app:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: npm i -g lerna
      - run: npm run bootstrap
      - run: npm run build:app
      - name: Build with netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=packages/app/build
        env:
          REACT_APP_GRAPHQL_URL: https://api.edg.sh/
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  deploy-landing:
    name: Deploy Landing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: npm i -g lerna
      - run: npm run bootstrap
      - run: npm run build:landing
      - name: Build with netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=packages/app/build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_LANDING_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
